# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/txia23/anaconda3/bin/cmake

# The command to remove a file.
RM = /home/txia23/anaconda3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/txia23/quantum/EMSolver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/txia23/quantum/EMSolver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/txia23/anaconda3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/txia23/anaconda3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/txia23/anaconda3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/txia23/anaconda3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/txia23/anaconda3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/txia23/anaconda3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/txia23/anaconda3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/txia23/anaconda3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/txia23/quantum/EMSolver/CMakeFiles /home/txia23/quantum/EMSolver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/txia23/quantum/EMSolver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FDTD2D_3

# Build rule for target.
FDTD2D_3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FDTD2D_3
.PHONY : FDTD2D_3

# fast build rule for target.
FDTD2D_3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_3.dir/build.make CMakeFiles/FDTD2D_3.dir/build
.PHONY : FDTD2D_3/fast

#=============================================================================
# Target rules for targets named FDTD2D_1

# Build rule for target.
FDTD2D_1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FDTD2D_1
.PHONY : FDTD2D_1

# fast build rule for target.
FDTD2D_1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_1.dir/build.make CMakeFiles/FDTD2D_1.dir/build
.PHONY : FDTD2D_1/fast

#=============================================================================
# Target rules for targets named FDTD1D_3

# Build rule for target.
FDTD1D_3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FDTD1D_3
.PHONY : FDTD1D_3

# fast build rule for target.
FDTD1D_3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_3.dir/build.make CMakeFiles/FDTD1D_3.dir/build
.PHONY : FDTD1D_3/fast

#=============================================================================
# Target rules for targets named FDTD2D_2

# Build rule for target.
FDTD2D_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FDTD2D_2
.PHONY : FDTD2D_2

# fast build rule for target.
FDTD2D_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_2.dir/build.make CMakeFiles/FDTD2D_2.dir/build
.PHONY : FDTD2D_2/fast

#=============================================================================
# Target rules for targets named FDTD1D_2

# Build rule for target.
FDTD1D_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FDTD1D_2
.PHONY : FDTD1D_2

# fast build rule for target.
FDTD1D_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_2.dir/build.make CMakeFiles/FDTD1D_2.dir/build
.PHONY : FDTD1D_2/fast

#=============================================================================
# Target rules for targets named FDTD1D_1

# Build rule for target.
FDTD1D_1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FDTD1D_1
.PHONY : FDTD1D_1

# fast build rule for target.
FDTD1D_1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_1.dir/build.make CMakeFiles/FDTD1D_1.dir/build
.PHONY : FDTD1D_1/fast

examples/FDTD1D_1.o: examples/FDTD1D_1.cpp.o

.PHONY : examples/FDTD1D_1.o

# target to build an object file
examples/FDTD1D_1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_1.dir/build.make CMakeFiles/FDTD1D_1.dir/examples/FDTD1D_1.cpp.o
.PHONY : examples/FDTD1D_1.cpp.o

examples/FDTD1D_1.i: examples/FDTD1D_1.cpp.i

.PHONY : examples/FDTD1D_1.i

# target to preprocess a source file
examples/FDTD1D_1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_1.dir/build.make CMakeFiles/FDTD1D_1.dir/examples/FDTD1D_1.cpp.i
.PHONY : examples/FDTD1D_1.cpp.i

examples/FDTD1D_1.s: examples/FDTD1D_1.cpp.s

.PHONY : examples/FDTD1D_1.s

# target to generate assembly for a file
examples/FDTD1D_1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_1.dir/build.make CMakeFiles/FDTD1D_1.dir/examples/FDTD1D_1.cpp.s
.PHONY : examples/FDTD1D_1.cpp.s

examples/FDTD1D_2.o: examples/FDTD1D_2.cpp.o

.PHONY : examples/FDTD1D_2.o

# target to build an object file
examples/FDTD1D_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_2.dir/build.make CMakeFiles/FDTD1D_2.dir/examples/FDTD1D_2.cpp.o
.PHONY : examples/FDTD1D_2.cpp.o

examples/FDTD1D_2.i: examples/FDTD1D_2.cpp.i

.PHONY : examples/FDTD1D_2.i

# target to preprocess a source file
examples/FDTD1D_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_2.dir/build.make CMakeFiles/FDTD1D_2.dir/examples/FDTD1D_2.cpp.i
.PHONY : examples/FDTD1D_2.cpp.i

examples/FDTD1D_2.s: examples/FDTD1D_2.cpp.s

.PHONY : examples/FDTD1D_2.s

# target to generate assembly for a file
examples/FDTD1D_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_2.dir/build.make CMakeFiles/FDTD1D_2.dir/examples/FDTD1D_2.cpp.s
.PHONY : examples/FDTD1D_2.cpp.s

examples/FDTD1D_3.o: examples/FDTD1D_3.cpp.o

.PHONY : examples/FDTD1D_3.o

# target to build an object file
examples/FDTD1D_3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_3.dir/build.make CMakeFiles/FDTD1D_3.dir/examples/FDTD1D_3.cpp.o
.PHONY : examples/FDTD1D_3.cpp.o

examples/FDTD1D_3.i: examples/FDTD1D_3.cpp.i

.PHONY : examples/FDTD1D_3.i

# target to preprocess a source file
examples/FDTD1D_3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_3.dir/build.make CMakeFiles/FDTD1D_3.dir/examples/FDTD1D_3.cpp.i
.PHONY : examples/FDTD1D_3.cpp.i

examples/FDTD1D_3.s: examples/FDTD1D_3.cpp.s

.PHONY : examples/FDTD1D_3.s

# target to generate assembly for a file
examples/FDTD1D_3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD1D_3.dir/build.make CMakeFiles/FDTD1D_3.dir/examples/FDTD1D_3.cpp.s
.PHONY : examples/FDTD1D_3.cpp.s

examples/FDTD2D_1.o: examples/FDTD2D_1.cpp.o

.PHONY : examples/FDTD2D_1.o

# target to build an object file
examples/FDTD2D_1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_1.dir/build.make CMakeFiles/FDTD2D_1.dir/examples/FDTD2D_1.cpp.o
.PHONY : examples/FDTD2D_1.cpp.o

examples/FDTD2D_1.i: examples/FDTD2D_1.cpp.i

.PHONY : examples/FDTD2D_1.i

# target to preprocess a source file
examples/FDTD2D_1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_1.dir/build.make CMakeFiles/FDTD2D_1.dir/examples/FDTD2D_1.cpp.i
.PHONY : examples/FDTD2D_1.cpp.i

examples/FDTD2D_1.s: examples/FDTD2D_1.cpp.s

.PHONY : examples/FDTD2D_1.s

# target to generate assembly for a file
examples/FDTD2D_1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_1.dir/build.make CMakeFiles/FDTD2D_1.dir/examples/FDTD2D_1.cpp.s
.PHONY : examples/FDTD2D_1.cpp.s

examples/FDTD2D_2.o: examples/FDTD2D_2.cpp.o

.PHONY : examples/FDTD2D_2.o

# target to build an object file
examples/FDTD2D_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_2.dir/build.make CMakeFiles/FDTD2D_2.dir/examples/FDTD2D_2.cpp.o
.PHONY : examples/FDTD2D_2.cpp.o

examples/FDTD2D_2.i: examples/FDTD2D_2.cpp.i

.PHONY : examples/FDTD2D_2.i

# target to preprocess a source file
examples/FDTD2D_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_2.dir/build.make CMakeFiles/FDTD2D_2.dir/examples/FDTD2D_2.cpp.i
.PHONY : examples/FDTD2D_2.cpp.i

examples/FDTD2D_2.s: examples/FDTD2D_2.cpp.s

.PHONY : examples/FDTD2D_2.s

# target to generate assembly for a file
examples/FDTD2D_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_2.dir/build.make CMakeFiles/FDTD2D_2.dir/examples/FDTD2D_2.cpp.s
.PHONY : examples/FDTD2D_2.cpp.s

examples/FDTD2D_3.o: examples/FDTD2D_3.cpp.o

.PHONY : examples/FDTD2D_3.o

# target to build an object file
examples/FDTD2D_3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_3.dir/build.make CMakeFiles/FDTD2D_3.dir/examples/FDTD2D_3.cpp.o
.PHONY : examples/FDTD2D_3.cpp.o

examples/FDTD2D_3.i: examples/FDTD2D_3.cpp.i

.PHONY : examples/FDTD2D_3.i

# target to preprocess a source file
examples/FDTD2D_3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_3.dir/build.make CMakeFiles/FDTD2D_3.dir/examples/FDTD2D_3.cpp.i
.PHONY : examples/FDTD2D_3.cpp.i

examples/FDTD2D_3.s: examples/FDTD2D_3.cpp.s

.PHONY : examples/FDTD2D_3.s

# target to generate assembly for a file
examples/FDTD2D_3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FDTD2D_3.dir/build.make CMakeFiles/FDTD2D_3.dir/examples/FDTD2D_3.cpp.s
.PHONY : examples/FDTD2D_3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... FDTD1D_1"
	@echo "... FDTD1D_2"
	@echo "... FDTD1D_3"
	@echo "... FDTD2D_1"
	@echo "... FDTD2D_2"
	@echo "... FDTD2D_3"
	@echo "... examples/FDTD1D_1.o"
	@echo "... examples/FDTD1D_1.i"
	@echo "... examples/FDTD1D_1.s"
	@echo "... examples/FDTD1D_2.o"
	@echo "... examples/FDTD1D_2.i"
	@echo "... examples/FDTD1D_2.s"
	@echo "... examples/FDTD1D_3.o"
	@echo "... examples/FDTD1D_3.i"
	@echo "... examples/FDTD1D_3.s"
	@echo "... examples/FDTD2D_1.o"
	@echo "... examples/FDTD2D_1.i"
	@echo "... examples/FDTD2D_1.s"
	@echo "... examples/FDTD2D_2.o"
	@echo "... examples/FDTD2D_2.i"
	@echo "... examples/FDTD2D_2.s"
	@echo "... examples/FDTD2D_3.o"
	@echo "... examples/FDTD2D_3.i"
	@echo "... examples/FDTD2D_3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

